version: '2'
services:
  telly:
    image: dafal/telly:latest
    restart: unless-stopped
    ports:
     - 6077:6077
  streamlink-laune:
    image: dafal/streamlink:latest
    restart: unless-stopped
    command: 'http://rtbf.l3.freecaster.net/live/rtbf/geo/drm/laune-audio_1=128000-video=2000000.m3u8 best' 
  streamlink-ladeux:
    image: dafal/streamlink:latest
    restart: unless-stopped
    command: 'http://rtbf.l3.freecaster.net/live/rtbf/geo/drm/ladeux-audio_1=128000-video=2000000.m3u8 best'
  streamlink-latrois:
    image: dafal/streamlink:latest
    restart: unless-stopped
    command: 'http://rtbf.l3.freecaster.net/live/rtbf/geo/drm/ladeux-audio_1=128000-video=2000000.m3u8 best' 
  streamlink-arte:
    image: dafal/streamlink:latest
    restart: unless-stopped
    command: 'https://www.arte.tv/fr/direct/ best'
  streamlink-euronews:
    image: dafal/streamlink:latest
    restart: unless-stopped
    command: 'https://fr.euronews.com/live best'
  streamlink-tv5:
    image: dafal/streamlink:latest
    restart: unless-stopped
    command: '--http-proxy http://fr-proxy:8888 http://live.tv5monde.com/fbs.html best'
  streamlink-france2:
    image: dafal/streamlink:latest
    restart: unless-stopped
    command: '--http-proxy http://fr-proxy:8888 https://www.france.tv/france-2/direct.html best'
  streamlink-france3:
    image: dafal/streamlink:latest
    restart: unless-stopped
    command: '--http-proxy http://fr-proxy:8888 https://www.france.tv/france-3/direct.html best'
  streamlink-france4:
    image: dafal/streamlink:latest
    restart: unless-stopped
    command: '--http-proxy http://fr-proxy:8888 https://www.france.tv/france-4/direct.html best'
  streamlink-france5:
    image: dafal/streamlink:latest
    restart: unless-stopped
    command: '--http-proxy http://fr-proxy:8888 https://www.france.tv/france-5/direct.html best'
  streamlink-franceo:
    image: dafal/streamlink:latest
    restart: unless-stopped
    command: '--http-proxy http://fr-proxy:8888 https://www.france.tv/france-o/direct.html best'

